/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ctpv;

import java.io.DataInputStream;
import java.io.ObjectInputStream;
import java.net.Socket;

/**
 *
 * @author chovi_000
 */
//Esta es la internalframe que aparecerá en el terminal CTPV
public class VentanaInterna extends javax.swing.JInternalFrame {

    private String nombre;
    private int indice;
    private Socket socket;
    private ObjectInputStream InputDatoRecibido;
    private HiloEscuchaTPV hiloescucha;
    
    /**
     * Para lectura de datos en el socket
     */
    private DataInputStream dataInput;

    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
        //setFrameIcon(new ImageIcon(this.getClass().getResource("..\\TPV\\src\\Iconos\\Productos.png")));
       
        setVisible(true);
    }

    public VentanaInterna(int indice) {
        this();
        this.indice = indice;
        ponerNombre();
        setVisible(true);
    }



    private void ponerNombre() {
        int aux = this.indice + 1;
        this.nombre = "Terminal TPV " + aux;
        setTitle("Terminal TPV " + aux);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTotalTicket = new javax.swing.JLabel();
        jScrollPaneTicketCompra = new javax.swing.JScrollPane();
        jList1TicketCompra = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));

        jLabelTotalTicket.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTotalTicket.setText("TOTAL");
        jLabelTotalTicket.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Ticket"));

        jScrollPaneTicketCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Ticket Compra"));
        jScrollPaneTicketCompra.setPreferredSize(new java.awt.Dimension(285, 300));
        jScrollPaneTicketCompra.setWheelScrollingEnabled(false);

        jList1TicketCompra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jList1TicketCompra.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1TicketCompra.setFocusable(false);
        jList1TicketCompra.setMaximumSize(new java.awt.Dimension(10000, 10000));
        jList1TicketCompra.setPreferredSize(new java.awt.Dimension(200, 300));
        jList1TicketCompra.setValueIsAdjusting(true);
        jList1TicketCompra.setVisibleRowCount(6);
        jScrollPaneTicketCompra.setViewportView(jList1TicketCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneTicketCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabelTotalTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneTicketCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTotalTicket;
    private javax.swing.JList jList1TicketCompra;
    private javax.swing.JScrollPane jScrollPaneTicketCompra;
    // End of variables declaration//GEN-END:variables

    
    // ----------- Getters y Setters -------------

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getIndice() {
        return indice;
    }

    public void setIndice(int indice) {
        this.indice = indice;
    }

    public Socket getSocket() {
        return socket;
    }

    public void setSocket(Socket socket) {
        this.socket = socket;
    }

    public ObjectInputStream getInputDatoRecibido() {
        return InputDatoRecibido;
    }

    public void setInputDatoRecibido(ObjectInputStream InputDatoRecibido) {
        this.InputDatoRecibido = InputDatoRecibido;
    }

    public HiloEscuchaTPV getHiloescucha() {
        return hiloescucha;
    }

    public void setHiloescucha(HiloEscuchaTPV hiloescucha) {
        this.hiloescucha = hiloescucha;
    }

    public DataInputStream getDataInput() {
        return dataInput;
    }

    public void setDataInput(DataInputStream dataInput) {
        this.dataInput = dataInput;
    }

    public javax.swing.JLabel getjLabelTotalTicket() {
        return jLabelTotalTicket;
    }

    public void setjLabelTotalTicket(javax.swing.JLabel jLabelTotalTicket) {
        this.jLabelTotalTicket = jLabelTotalTicket;
    }

    public javax.swing.JList getjList1TicketCompra() {
        return jList1TicketCompra;
    }

    public void setjList1TicketCompra(javax.swing.JList jList1TicketCompra) {
        this.jList1TicketCompra = jList1TicketCompra;
    }

    public javax.swing.JScrollPane getjScrollPaneTicketCompra() {
        return jScrollPaneTicketCompra;
    }

    public void setjScrollPaneTicketCompra(javax.swing.JScrollPane jScrollPaneTicketCompra) {
        this.jScrollPaneTicketCompra = jScrollPaneTicketCompra;
    }
    
}
